### ISSUE TITLE
Weird error messages showing up on logs

### ISSUE THREAD

**Issue by joshuadeguzman** [superwall/Superwall-Flutter#19]
### Description

I followed the steps thoroughly in [this guide](https://superwall.com/docs/flutter). However, we're seeing some messages when we're trying to present the paywall in debug mode:

![Screenshot 2024-07-31 at 9 49 51 PM](https://github.com/user-attachments/assets/8a24a5bb-4815-48d9-966d-c8ef93d5da41)

I tried looking for the same message on the [Flutter SDK](https://github.com/superwall/Superwall-Flutter), [Android SDK](https://github.com/superwall/Superwall-Android), [iOS SDK](https://github.com/superwall/Superwall-iOS).

Can you help us verify where this messages/logs are coming from?

**Comment by lukemmtt** [comment]
Fellow sdk user here—these print statements were erroneously introduced in release 1.1.9, and mostly removed in [release 1.2.0](https://github.com/superwall/Superwall-Flutter/releases/tag/1.2.0) (specifically PR https://github.com/superwall/Superwall-Flutter/pull/12) and completely removed in https://github.com/superwall/Superwall-Flutter/pull/13 (which hasn't been rolled into a release yet).

If you haven't updated the SDK in the last 2 weeks, updating it, might fix it, so long as your flutter-android project is using a Gradle version older than 8.1.0. But if it's not, you'll be stuck at release 1.1.9, and stuck with these print statements. I was in that situation before, and made a fork with the print statements removed here: https://github.com/TimeFinderApp/Superwall-Flutter/commit/e8c6d03273086745b8637afab65d2e1f9feac335.

Hope that helps!

**Comment by joshuadeguzman** [comment]
> Fellow sdk user here—these print statements were erroneously introduced in release 1.1.8, and mostly removed in release 1.1.9 (specifically PR https://github.com/superwall/Superwall-Flutter/pull/12) and fully removed in 1.2.0.

Thanks @lukemmtt. That make sense. I couldn't find it elsewhere on the code before.

> I was in that situation before, and made a fork of 1.1.8 with the print statements removed here: https://github.com/TimeFinderApp/Superwall-Flutter/commit/e8c6d03273086745b8637afab65d2e1f9feac335.

 Yeah I reported a similar issue regarding the old version of the SDK, they updated the doc since. 

Awesome app, good luck on your project!

**Comment by lukemmtt** [comment]
Glad I could help @joshuadeguzman! 

> Yeah I reported a similar issue regarding the old version of the SDK, they updated the doc since.

Makes sense. Yeah the Superwall guys are great despite definitely having their hands full! 

> Awesome app, good luck on your project!

Thank you very much! Dub looks incredible too, best of luck!

**Comment by ianrumac** [comment]
Thank you @lukemmtt for helping resolve this!

**Comment by jakemor** [comment]
Much love Luke, thanks for the kind words :) nice to see people in our community helping one another!

**Comment by lukemmtt** [comment]
@jakemor Glad to help, thanks for the product sir!
