### ISSUE TITLE
Null Value Returned on Server-Side After Subscription

### ISSUE THREAD

**Issue by DaxeshV** [superwall/Superwall-Flutter#31]
We are using Superwall for handling subscriptions in our app. After a subscription is successfully completed, we are passing the following line to identify the user:

`await Superwall.shared.identify(rcPurchaseController.getUserKey());`

However, on the server-side, we’re receiving a null value for the user key, which should not be happening. The getUserKey() function is correctly fetching the user key locally, but it is not being transmitted properly to the server.

Environment:

	•	Superwall Version: superwallkit_flutter: ^1.3.0
	•	Platform: Android & iOS

Any guidance on this issue would be appreciated!

**Comment by ianrumac** [comment]
Hey @DaxeshV,

Thanks for the request -  in the latest version, we have added an option in `SuperwallOptions` called `passIdentifiersToPlayStore` which enables you to pass user identifiers (using `Superwall.shared.identify` to the Google Play store as user accountId's which you should then be able to receive on the backend.

Hope this solves your issue!
