### ISSUE TITLE
[Flutter] - Getting error when dismissing superwall screen

### ISSUE THREAD

**Issue by harrylefit** [superwall/Superwall-Flutter#7]
You can check it.

![telegram-cloud-photo-size-5-6078164733376183094-y](https://github.com/superwall/Superwall-Flutter/assets/20136040/87187024-e13d-4acd-8b96-48ac98dc2cf2)

**Comment by yusuftor** [comment]
This should be fixed in the latest release v1.1.1. Thanks for reporting!
