### ISSUE TITLE
Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'

### ISSUE THREAD

**Issue by pam3ec555** [superwall/Superwall-Flutter#8]
Hello. I have an error while trying to start the project on android:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDevDebugAarMetadata'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not find com.superwall.sdk:superwall-android:1.1.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/superwall/sdk/superwall-android/1.1.1/superwall-android-1.1.1.pom
       - https://repo.maven.apache.org/maven2/com/superwall/sdk/superwall-android/1.1.1/superwall-android-1.1.1.pom
       - https://storage.googleapis.com/download.flutter.io/com/superwall/sdk/superwall-android/1.1.1/superwall-android-1.1.1.pom
       - https://jcenter.bintray.com/com/superwall/sdk/superwall-android/1.1.1/superwall-android-1.1.1.pom
       - https://jitpack.io/com/superwall/sdk/superwall-android/1.1.1/superwall-android-1.1.1.pom
     Required by:
         project :app > project :superwallkit_flutter

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
Error: Gradle task assembleDevDebug failed with exit code 1

**Comment by yusuftor** [comment]
Hi, it looks like you might not have included out custom android repo in your build.gradle. However, you shouldn't need to do that anymore with the latest versions of the SDK. Does this still happen?

**Comment by pam3ec555** [comment]
Hello, Error is gone on the latest version of the package. Thank you
